# builder IP & HTTP server port serving
# the content of 'build_base_dir'
build_base_url: "http://{{ansible_default_ipv4.address}}:8000"
# htdocs dir path on builder
build_base_dir: '/root/data'
#build_uuid_generator: 'uuidgen'
# this key will be temporarily pushed into created VMs,
# so ansible can log in an configure them
build_ssh_key: 'ssh-rsa root user@host'
# root pwd that will be set in VMs
build_image_password: 'nbusr123'
build_disk_compression: lz4

build_resolvers:
  - 8.8.8.8
  - 8.8.4.4

# nic tag of the interface on buildhost which will be used by VMs to access the network
build_nic_tag: admin
# network config of VMs
build_gateway: 10.12.14.1
build_netmask: 255.255.254.0
