- name: install cloud init
  package:
    name: cloud-init
    state: latest

- name: copy over base cloud init config
  copy:
    src: cloud.cfg
    dest: /etc/cloud/cloud.cfg
    mode: 0644

- name: copy the lvextend script
  copy:
    src: scripts/expandlvs.sh
    dest: /var/lib/cloud/scripts/per-boot/expandlvs.sh
    mode: a+x

- name: reboot server
 command: /sbin/reboot
 async: 0
 poll: 0
 ignore_errors: yes

- name: wait for reboot
  pause:
    minutes: 1
  
- name: Ensure port is open on server
  wait_for:
    host: "{{ buildnode }}"
    port: 22
    state: started
  delegate_to: "{{ builder }}"
