- name: install cloud init
  package:
    name: cloud-init
    state: latest

- name: copy over base cloud init config
  copy:
    src: cloud.cfg
    dest: /etc/cloud/cloud.cfg
    mode: 0644

- name: Install mdata
  package:
    name: joyent-mdata-client
    state: latest

- name: reboot server
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0
  ignore_errors: yes

- name: wait for server to reboot
  pause:
    minutes: 1
  
