- name: install cloud init
  package:
    name: cloud-init
    state: latest

- name: copy over base cloud init config
  copy:
    src: cloud.cfg
    dest: /etc/cloud/cloud.cfg
    mode: 0644

- name: Install make and git
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - make
    - git

- name: Install mdata using script
  script: mdatainstall.sh

- name: reboot server
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0
  ignore_errors: yes

- name: wait for server to reboot
  pause:
    minutes: 1
  
