- name: install cloud init
  package:
    name: cloud-init
    state: latest

- name: copy over base cloud init config
  copy:
    src: cloud.cfg
    dest: /etc/cloud/cloud.cfg
    mode: 0644

- name: copy the lvextend script
  copy:
    src: scripts/expandlvs.sh
    dest: /var/lib/cloud/scripts/per-boot/expandlvs.sh
    mode: a+x

- name: reboot server
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0
  ignore_errors: yes
  
- name: Ensure port is open on server
  local_action: wait_for
  args:
    host: "{{ buildnode }}"
    port: 22
    state: started
    delay: 30
    timeout: 300
  delegate_to: "{{ builder }}"
