- name: install cloud init
  package:
    name: cloud-init
    state: latest

- name: copy over base cloud init config
  copy:
    src: cloud.cfg
    dest: /etc/cloud/cloud.cfg
    mode: 0644

- name: Install make and git
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - make
    - git
    - gcc

- name: Install mdata using script
  script: mdatainstall.sh

- name: Remove any non-used distros in cloud init 
  lineinfile:
    path: /etc/cloud/cloud.cfg.d/90_dpkg.cfg
    regexp: '^datasource'
    line: 'datasource_list: [ SmartOS, None ]'
  

- name: reboot server
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0
  ignore_errors: yes

- name: wait for server to reboot
  pause:
    minutes: 1
  
- name: Add authorized key to root
  shell: mdata-get root_authorized_keys >> /root/.ssh/authorized_keys