- name: install cloud init
  package:
    name: cloud-init
    state: latest

- name: reboot server
  shell: reboot
  ignore_errors: yes

- name: wait for reboot
  pause:
    minutes: 2

- name: Ensure port is open on server
  wait_for:
    host: "{{ buildnode }}"
    port: 22
  delegate_to: "{{ builder }}"
