- name: install cloud init
  package:
    name: cloud-init
    state: latest

- name: reboot server
  shell: reboot
  ignore_errors: yes

- name: wait for server to come back online
  local_action: wait_for state=started host={{ passtemplate }}
