- name: Create image file 

- name: Get UUID
  command: bash -c "vmadm list alias=template |grep '[a-d0-9]-'|cut -d' ' -f1"
  register: uuid_output

- name:
  set_fact:
    template_uuid: "{{ uuid_output.stdout }}"

- name: Stop virtual machine
  vmadm: uuid="{{ template_uuid }}" state=stopped

- name: Create directory /opt/{{ template_uuid }}
  file: path="/opt/{{ template_uuid }}" state=directory

- name: Create image {{ image_name }}
  command: chdir="/opt/{{ template_uuid }}" imgadm create -c gzip "{{ template_uuid }}"
           name='Ububntu'
           version='16.04'
           tags=''
           published_at="{{ lookup('pipe', 'date -u +\"%Y-%m-%dT%H:%M:%SZ\"') }}"
           os=linux
           type=zvol
           nic_driver=virtio
           disk_driver=virtio
           cpu_type=qemu64
           image_size="10G"
           state="active"
           disabled="false"
           description="Base Ubuntu Image"
           homepage="http://mnx.io"
 
