- name: Get UUID
  command: bash -c "vmadm list alias=template |grep '[a-d0-9]-'|cut -d' ' -f1"
  register: uuid_output

- name:
  set_fact:
    template_uuid: "{{ uuid_output.stdout }}"

- name: Stop virtual machine
  vmadm: uuid="{{ template_uuid }}" state=stopped

- name: Create directory /opt/{{ template_uuid }}
  file: path="/opt/{{ template_uuid }}" state=directory

- name: Create image {{ image_name }}
  command: chdir="/opt/{{ template_uuid }}" imgadm create -c gzip "{{ template_uuid }}"
           name="{{ image_name }}"
           version="{{ image_version }}"
           published_at="{{ lookup('pipe', 'date -u +\"%Y-%m-%dT%H:%M:%SZ\"') }}"
           os=linux
           type=zvol
           nic_driver=virtio
           disk_driver=virtio
           cpu_type=qemu64
           image_size="10000"
           state="active"
           disabled="false"
           description="Base Ubuntu Image"
           homepage="http://mnx.io"

- name: Send image to image server
  command: "curl -v -u admintoken: http://10.12.15.36:5000/api/upload -F manifest=@/opt/{{ template_uuid }}/{{ image_name }}-{{ image_version }}.imgmanifest -Ffile=@/opt/{{ template_uuid }}/{{ image_name }}-{{ image_version }}.zvol.gz"

- name: ask to delete temp
  pause:
    prompt: Press enter to delete the template vm, or Ctrl-A to abort

- name: Remove virtual machine
  vmadm: 
    name: "{{ template_uuid }}" 
    state: absent
