

- name: update package manager for redhat based
  command: "yum update -y"
  when: ansible_os_family == "RedHat"

- name: update package manager for debian based
  command: "apt-get update -y"
  when: ansible_os_family == "Debian"

# Ensure latest kernel is loaded at boot
- name: Run GRUB load script
  script: grubmenu.sh
  ignore_errors: yes

- name: clean yum
  command: "yum clean all"
  when: ansible_os_family == "RedHat"

- name: clean apt
  command: "apt-get clean"
  when: ansible_os_family == "Debian"

- name: Clear temp dirs
  file:
    path: "/tmp/*"
    state: absent

- name: Clear wtmp and btmp
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    -  "/var/log/wtmp"
    -  "/var/log/btmp"

- name: Touch wtmp and btmp
  file:
    path: "{{ item }}"
    state: touch
  with_items:
    -  "/var/log/wtmp"
    -  "/var/log/btmp"

- name: Remove bash history
  file:
    path: "/root/.bash_history"
    state: absent

- name: Clear history
  command: bash -c 'history -c'

- name: Remove any previous cloud-init data
  file: 
    path: "/var/lib/cloud/instances/"
    state: absent
    recursive: yes

- name: Delete Template user 
  user:
    name: template
    state: absent
    remove: yes

- name: copy the lvextend script
  copy:
    src: scripts/expandlvs.sh
    dest: /var/lib/cloud/scripts/per-boot/expandlvs.sh
    mode: a+x

- name: copy the setrootpw script
  copy:
    src: scripts/setrootpw.sh
    dest: /var/lib/cloud/scripts/per-boot/setrootpw.sh
    mode: a+x

- name: copy the setupdns script
  copy:
    src: scripts/setupdns.sh
    dest: /var/lib/cloud/scripts/per-boot/setupdns.sh
    mode: a+x

- name: Prepare SSH
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/ssh/moduli"
    - "/etc/ssh/ssh_host_*"
    - "/root/.lesshst"
    
- name: Delete authorized keys file and blank root password
  shell: sleep 2 && rm -f /root/.ssh/authorized_keys && passwd -dl root
  async: 1
  poll: 0
  ignore_errors: yes
