- name: Check builder host
  hosts: builder
  tasks:
    - include: tasks/build/check.yml
      when: skip_check is not defined or not skip_check


- name: Create VM
  hosts: buildnode
  # vars_files:
  #   - vars/build/vm/ubuntu-16.04.yml
  roles:
    - smartos-vm

- name: Use password to install cloud-init and reboot
  hosts: passtemplate
  roles:
    - pass-build

- name: Connect via key and finish build
  hosts: keytemplate
  roles:
    - key-build






# #Split this up into pre tasks, tasks, final tasks
# - name: Create virtual machine and image
#   hosts: buildnode
#   vars_files:
#     - vars/build/vm/ubuntu-16.04.yml
#   pre_tasks:
#     - include: tasks/build/cleanup.yml
#   roles:
#     - smartos-vm
#   tasks:
#     - include: tasks/build/ubuntu-16.04/create-image.yml
