
- name: Create VM (KVM) configuration file
  template: src=kvm.json.j2
            dest=/tmp/base.json
            validate="vmadm validate create kvm -f %s"

- name: Create the virtual machine
  vmadm: manifest={{ item }} state=present
  with_items:
    - /tmp/base.json

- name: Get UUID
  command: bash -c "vmadm list alias=template |grep '[a-d0-9]-'|cut -d' ' -f1"
  register: uuid_output

- name:
  set_fact:
    template_uuid: "{{ uuid_output.stdout }}"

- debug:
    msg: "{{ template_uuid }}"

- name: Copy the iso to the correct locaion
  get_url:
    url: http://10.12.15.36:8000/isos/{{ iso_file }}
    dest: /zones/{{ template_uuid }}/root/
    mode: 0440
  
- name: Boot the vm with the new iso
  command: bash -c "vmadm boot {{template_uuid}} order=cd,once=d cdrom=/{{ iso_file }},ide"

- name: Pause for the build to be done
  pause:
    prompt: Press any key when build is done to continue

- name: delete local known host entry
  lineinfile:
    path: ~/.ssh/known_hosts
    regexp: '^10.12.15.199'
    state: absent
  delegate_to: builder


# The setup is done and now the OS Specific additions need to be added.
