
- name: Create VM (KVM) configuration file
  template: src=kvm.json.j2
            dest=/tmp/base.json
            validate="vmadm validate create kvm -f %s"
  when: zone_brand == "kvm"

- name: Create the virtual machine
  vmadm: manifest={{ item }} state=present
  with_items:
    - /tmp/base.json

- name: Get UUID
  command: bash -c "vmadm list alias=template |grep '[a-d0-9]-'|cut -d' ' -f1"
  register: uuid_output

- name:
  set_fact:
    template_uuid: "{{ uuid_output.stdout }}"

- debug:
    msg: "{{ template_uuid }}"

- name: Copy the iso to the correct locaion
  get_url:
    url: http://10.12.15.36:8000/isos/ubuntu.iso
    dest: /zones/{{ template_uuid }}/root/
    mode: 0440
  
- name: Boot the vm with the new iso
  command: bash -c "vmadm boot {{template_uuid}} order=cd,once=d cdrom=/ubuntu.iso,ide"

# - name: Ensure that virtual machine is running
#   vmadm: alias=template state=started
