
- name: Create VM (KVM) configuration file
  template: src=kvm.json.j2
            dest=/tmp/base.json
            validate="vmadm validate create kvm -f %s"
  when: zone_brand == "kvm"

- name: Create the virtual machine
  vmadm: manifest={{ item }} state=present
  with_items:
    - /tmp/base.json

- name: Ensure that virtual machine is running
  vmadm: alias=template state=started
