
- name: Create VM (KVM) configuration file
  template: src=kvm.json.j2
            dest=/tmp/base.json
            validate="vmadm validate create kvm -f %s"
  when: zone_brand == "kvm"

- name: Create the virtual machine
  vmadm: manifest={{ item }} state=present
  with_items:
    - /tmp/base.json

- name:
  set_fact:
    template_uuid: "vmadm list alias=elk.mnx.io |grep '[a-d0-9]-'|cut -d' ' -f1"

- debug:
    msg: "{{template_uuid }}"

- name: Copy the iso to the correct locaion
  get_url:
    url: http://10.12.15.36/iso/ubuntu.iso
    dest: /zones/{{ template_uuid }}/root/
    mode: 0440
  

# - name: Ensure that virtual machine is running
#   vmadm: alias=template state=started
